apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: test-ops-microservices
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /builder
    server: 192.168.1.17
